public_project/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.utils.translation import ugettext as _
from django.views.generic import TemplateView
from tastypie.api import Api
from public_project.api import *
from public_project.feeds import *
import public_project.views

handler404 = public_project.views.custom_404_view

urlpatterns = []

if getattr(settings, 'DPP_PUBLIC_API', False):
    v01_api = Api(api_name='v0.1')
    v01_api.register(ProjectPartsResource())
    v01_api.register(QuestionsResource())
    v01_api.register(ParticipantsResource())
    v01_api.register(EventsResource())
    v01_api.register(PagesResource())
    v01_api.register(DocumentsResource())
    
    urlpatterns = [
        url(r'^api/$', public_project.views.api),
        url(r'^api/', include(v01_api.urls)),
        url(r'^dev/logo/$', TemplateView.as_view(template_name="dev/logo.html")),
    ]

urlpatterns += [
    url(r'^xhr/universal_search/', public_project.views.xhr_universal_search, name='xhr_universal_search'),
    url(r'^xhr/document_tags/', public_project.views.xhr_document_tags, name='xhr_document_tags'),
    url(r'^$', public_project.views.index),
    url(r'^rss/$', ActivityFeed(None, '')),
    url(r'^%s$' % _('comments_url'), public_project.views.comments, {'object_id': None, 'content_type': None}),
    url(r'^%srss/$' % _('comments_url'), ActivityFeed('NC', _('comments_url'))),
    url(r'^404test/$', public_project.views.custom_404_view),
    #ProjectParts
    url(r'^%s$' % _('project_parts_url'), public_project.views.project_parts),
    url(r'^%srss/$' % _('project_parts_url'), ActivityFeed('NA', _('project_parts_url'))),
    url(r'^%s[a-z\d\-]+-(?P<project_part_id>\d+)/$' % _('project_parts_url'), public_project.views.project_part),
    url(r'^%s(?P<object_id>\d+)/%s$' % (_('project_parts_url'), _('comments_url')), public_project.views.comments, {'content_type': 'project_part'}),
    url(r'^%s(?P<object_id>\d+)/%srss/$' % (_('project_parts_url'), _('comments_url')), ProjectPartCommentsFeed()),
    url(r'^%s$' % _('goals_url'), public_project.views.goals),
    #Questions
    url(r'^%s$' % _('questions_url'), public_project.views.questions),
    url(r'^%s%s$' % (_('questions_url'), _('research_requests_url')), public_project.views.research_requests, {'object_id': None, 'content_type': None}),
    url(r'^%s%srss/$' % (_('questions_url'), _('research_requests_url')), ActivityFeed('RR', _('research_requests_url'))),
    url(r'^%s[a-z\d\-]+-(?P<question_id>\d+)/$' % _('questions_url'), public_project.views.question),
    url(r'^%s(?P<object_id>\d+)/%s$' % (_('questions_url'), _('research_requests_url')), public_project.views.research_requests, {'content_type': 'question'}),
    url(r'^%s(?P<object_id>\d+)/%srss/$' % (_('questions_url'), _('research_requests_url')), QuestionResearchRequestsFeed()),
    url(r'^%srss/$' % _('questions_url'), ActivityFeed('NQ', _('questions_url'))),
    url(r'^%s(?P<object_id>\d+)/%s$' % (_('questions_url'), _('comments_url')), public_project.views.comments, {'content_type': 'question'}),
    url(r'^%s(?P<object_id>\d+)/%srss/$' % (_('questions_url'), _('comments_url')), QuestionCommentsFeed()),
    #Events
    url(r'^%s$' % _('events_url'), public_project.views.events),
    url(r'^%srss/$' % _('events_url'), ActivityFeed('NE', _('events_url'))),
    url(r'^%s[a-z\d\-]+-(?P<event_id>\d+)/$' % _('events_url'), public_project.views.event),
    url(r'^%s(?P<object_id>\d+)/%s$' % (_('events_url'), _('comments_url')), public_project.views.comments, {'content_type': 'event'}),
    url(r'^%s(?P<object_id>\d+)/%srss/$' % (_('events_url'), _('comments_url')), EventCommentsFeed()),
    #Participants
    url(r'^%s$' % _('participants_url'), public_project.views.participants),
    url(r'^%srss/$' % _('participants_url'), ActivityFeed('PA', _('participants_url'))),
    url(r'^%s[a-z\d\-]+-(?P<participant_id>\d+)/$' % _('participants_url'), public_project.views.participant),
    url(r'^%s(?P<object_id>\d+)/%s$' % (_('participants_url'), _('comments_url')), public_project.views.comments, {'content_type': 'participant'}),
    url(r'^%s(?P<object_id>\d+)/%srss/$' % (_('participants_url'), _('comments_url')), ParticipantCommentsFeed()),
    
    url(r'^%s(?P<web_source_id>\d+)/$' % _('web_sources_url'), public_project.views.web_source),
    
    #Documents
    url(r'^%s$' % _('documents_url'), public_project.views.documents),
    url(r'^%srss/$' % _('documents_url'), ActivityFeed('ND', _('documents_url'))),
    url(r'^%s[a-z\d\-]+-(?P<document_id>\d+)/$' % _('documents_url'), public_project.views.document),
    url(r'^%s(?P<object_id>\d+)/%s$' % (_('documents_url'), _('comments_url')), public_project.views.comments, {'content_type': 'document'}),
    url(r'^%s(?P<object_id>\d+)/%srss/$' % (_('documents_url'), _('comments_url')), DocumentCommentsFeed()),
    url(r'^%s$' %  _('search_url'), public_project.views.search),
    url(r'^%s$' % _('contact_url'), public_project.views.contact),
    url(r'^%s$' % _('activate_comment_url'), public_project.views.activate_comment),
]
                       

public_project/models.py
# coding=UTF-8
import os
import shutil
import subprocess
from datetime import datetime
from itertools import chain

from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.sites.models import Site
from django.db import models
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver
from django.utils.text import slugify
from django.utils.translation import ugettext, ugettext_lazy as _
from django.utils.http import urlquote
from public_project.doc_scanner import DocScanner



class UserProfile(models.Model):
    user = models.OneToOneField(User)
    receive_new_comment_emails = models.BooleanField(default=True)


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)


class Image(models.Model):
    title = models.CharField(_("Title"), max_length=250)
    help_text = _("400px max width, 200px for images used with floating texts")
    image = models.ImageField(_("Image"), upload_to='images', help_text=help_text)
    help_text = _("Attribution to the original image source or alternatively something like 'Own image'.")
    attribution = models.CharField(_("Attribution"), max_length=250, help_text=help_text)
    help_text = _("Link to the original image source (if available)")
    attribution_url = models.URLField(_("Attribution URL"), help_text=help_text, blank=True, null=True)
    comments = models.TextField(_("Comments (internal)"), blank=True)
    
    def __unicode__(self):
        return self.title
    
    class Meta:
        ordering = ['title',]
        verbose_name = _('Image')
        verbose_name_plural = _('Images')


class SiteConfigManager(models.Manager):
    
    def get_site_config(self, request):
        if super(SiteConfigManager, self).count() == 0:
            site_config = SiteConfig()
            site_config.save()
        else:
            site_config = super(SiteConfigManager, self).all()[0]
        
        site_config.pdf_viewer = 'STANDARD'
        site_config.browser = 'Unknown'
        if request and 'HTTP_USER_AGENT' in request.META:
            if 'Mozilla'.lower() in request.META['HTTP_USER_AGENT'].lower():
                site_config.pdf_viewer = 'STANDARD'
                site_config.browser = 'Mozilla'
            if 'Safari'.lower() in request.META['HTTP_USER_AGENT'].lower():
                site_config.pdf_viewer = 'STANDARD'
                site_config.browser = 'Safari'
            if 'Chrome'.lower() in request.META['HTTP_USER_AGENT'].lower():
                site_config.pdf_viewer = 'STANDARD'
                site_config.browser = 'Chrome'
            if 'Opera'.lower() in request.META['HTTP_USER_AGENT'].lower():
                site_config.pdf_viewer = 'STANDARD'
                site_config.browser = 'Opera'
            if 'MSIE'.lower() in request.META['HTTP_USER_AGENT'].lower():
                if getattr(settings, 'DPP_IE_COMPATIBLE_PDF_VIEWER', False):
                    site_config.pdf_viewer = 'LEGACY'
                else:
                    site_config.pdf_viewer = False
                site_config.browser = 'MSIE'
        
        if getattr(settings, 'DPP_PUBLIC_API', False):
            site_config.public_api = True
        else:
            site_config.public_api = False
        
        if getattr(settings, 'DPP_CUSTOM_JS', False):
            site_config.custom_js = settings.DPP_CUSTOM_JS
        else:
            site_config.custom_js = ''    
        
        if getattr(settings, 'DPP_CUSTOM_CSS', False):
            site_config.custom_css = settings.DPP_CUSTOM_CSS
        else:
            site_config.custom_css = ''
        
        return site_config
    

class SiteConfig(models.Model):
    help_text = _("Main title, shown in the header navi.")
    default = _("Project Website Title")
    title = models.CharField(_("Title"), max_length=250, help_text=help_text, default=default)
    help_text = _("Short version of the title, used e.g. in emails.")
    default = _("Project Website Short Title")
    short_title = models.CharField(_("Short title"), max_length=250, help_text=help_text, default=default)
    help_text = _("Color for the page title (Format: '#990000').")
    title_color = models.CharField(_("Title color"), max_length=7, help_text=help_text, default='#990000')
    help_text = _("Show/use the Goals category in the project.")
    show_goals_category = models.BooleanField(default=True)
    help_text = _("Show/use the Questions category in the project.")
    show_questions_category = models.BooleanField(default=True)
    help_text = _("Activate user comments.")
    activate_comments = models.BooleanField(default=True)
    help_text = _("Short intro text to describe your page (HTML possible), not too long, use about text for detailed information.")
    default = _("This is a project watch website.")
    intro_text = models.TextField(_("Intro text"), help_text=help_text, default=default)
    help_text = _("Short intro text about this site, what is the purpose, who is running it.")
    default = _("About text")
    about_text = models.TextField(_("About text"), help_text=help_text, default=default)
    help_text = _("Some html text you want to use in the footer of the page, you can e.g. \
provide a link to your email adress or associated social media sites.")
    footer = models.TextField(_("Footer"), help_text=help_text, default=_("Footer HTML Default"))
    help_text = _("Html to be displayed on the contact page, provide at least an adress there \
and some contact information.")
    contact_text = models.TextField(_("Contact"), help_text=help_text, default=_("Contact HTML Default"))
    comments = models.TextField(_("Comments (internal)"), blank=True)
    
    objects = SiteConfigManager()
    
    def __unicode__(self):
        return self.title
    
    class Meta:
        verbose_name = _('Website Configuration')
        verbose_name_plural = _('Website Configuration')


class SiteCategory(models.Model):
    NAME_CHOICES = (
        ('home', "Home"),
        ('project_parts', _('Topics')),
        ('goals', _('Goals')),
        ('questions', _('Questions')),
        ('participants', _('Participants')),
        ('events', _('Events')),
        ('documents', _('Documents')),
    )
    category = models.CharField(_("Category"), max_length=50, choices=NAME_CHOICES, unique=True)
    intro_text = models.TextField(_("Intro text"), blank=True, null=True)
    documents = models.ManyToManyField('Document', related_name="related_site_categories", blank=True, verbose_name=_("Documents"))
    web_sources = GenericRelation('WebSource', verbose_name=_("Web Sources"))
    comments = models.TextField(_("Comments (internal)"), blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __unicode__(self):
        return self.get_category_display()
    
    class Meta:
        verbose_name = _('Website Category')
        verbose_name_plural = _('Website Categories')


class ParticipantType(models.Model):
    help_text = _("Type or category for sorting of participants")
    name = models.CharField(_("Title"), max_length=250, help_text=help_text)
    help_text = _("Use integer numbers for ordering (e.g. '100', '200', '300').")
    order = models.IntegerField(_("Order"), default=100)
    date_added = models.DateTimeField(auto_now_add=True)    
    
    def get_participants(self):
        return self.participant_set.filter(belongs_to=None)
    
    def __unicode__(self):
        return self.name
    
    class Meta:
        ordering = ['order']
        verbose_name = _('Type Participants')
        verbose_name_plural = _('Types Participants')


class WebSource(models.Model):
    title = models.CharField(_("Title"), max_length=250)
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")
    help_text = _("Use integer numbers for ordering (e.g. '100', '200', '300').")
    order = models.IntegerField(_("Order"), help_text=help_text, default=100, blank=True, null=True)
    url = models.URLField(_("URL"))
    date = models.DateField(_("Date"), blank=True, null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __unicode__(self):
        return self.title
    
    def get_absolute_url(self):
        return "/" + ugettext("web_sources_url") + unicode(self.id) + "/"
    
    @classmethod
    def get_icon_class(cls):
        return 'icon-globe'
    
    class Meta:
        ordering = ['order']
        verbose_name = _('Web-Source')
        verbose_name_plural = _('Web-Sources')


class Membership(models.Model):
    from_participant = models.ForeignKey('Participant', related_name='from_memberships', verbose_name=_("From participant"))
    help_text = _('Association with a group or institution')
    to_participant = models.ForeignKey('Participant', help_text=help_text, related_name='to_memberships', verbose_name=_("To participant"))
    help_text = _("Type or function of the membership or task or position of the participant.")
    function = models.CharField(_("Function"), max_length=50, help_text=help_text, blank=True, null=True)
    active = models.BooleanField(_("Active"), default=True)
    
    class Meta:
        verbose_name = _('Membership')
        verbose_name_plural = _('Memberships')


class Participant(models.Model):
    help_text  = _("Person, group or institution acting in some way in the context of the project or being affected by the process or the result of the project execution.")
    name = models.CharField(_("Name"), max_length=250, help_text=help_text, unique=True)

public_project/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
    

class CommentForm(forms.Form):
    username = forms.CharField()
    email = forms.EmailField()
    comment = forms.CharField(max_length=800)
    feedback_allowed = forms.BooleanField(required=False)
    co1_id = forms.IntegerField()
    co1_content_type = forms.CharField()
    co1_page = forms.IntegerField(required=False)
    

public_project/templates/dialogs/comment.html
{% load i18n %}
{% load bpw %}

{% if comment_form_status == 'SENT' %}
  {% trans "Thank you for your comment. You will receive an email when the commented was published by an administrative user." as confirm_text %}
  {% include "dialogs/generic_confirm.html" %}   
{% endif %}
{% if comment_form_status == 'FAILED' %}
  {% trans "There was an error and your comment could not be safed. Sorry! :-/" as confirm_text %}
  {% include "dialogs/generic_confirm.html" %}   
{% endif %}

<div class="modal fade" id="CommentModal">
  
  <div class="modal-dialog">
  <div class="modal-content" style="width:800px;">

  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3>{% trans "My Comment on" %}</h3>
    <h4><i class="{{ commented_object1.get_icon_class }}"></i> {{ commented_object1 }}<span id="co1_header_page"></span></h4>
  </div>
  
  <form enctype="multipart/form-data" class="form-horizontal" action="." method="post">
    <input type="hidden" id="id_co1_content_type" name="co1_content_type" value="{{ commented_object1|modelname }}">
    <input type="hidden" id="id_co1_id" name="co1_id" value="{{ commented_object1.id }}">
    {% with commented_object1|modelname as modelname %}
    {% if modelname == 'document' %}
       <input type="hidden" id="id_co1_page" name="co1_page" value="">
    {% endif %}
    {% endwith %}
  {% csrf_token %}
  <div class="modal-body" style="padding:0px;max-height:inherit;background-color: #fff;">
    <div style="padding:15px;">
    <div style="margin-top:10px;">
      <div style="float:left;margin-right:20px;">
      <textarea id="id_comment" class="form-control" style="width: 400px;height: 160px;" rows="10" cols="40" name="comment"></textarea>
      </div>
      <div>
        <fieldset>
        <div style="clear:both;">
          <div style="float:left;font-size:12px;">
            {% trans "Name" %}
          </div>
          <div style="float:right;width:280px;">
            <input id="id_username" class="form-control" type="text" name="username" maxlength="50">
            <span style="font-size:12px;">({% trans "required" %})</span>
          </div>
        </div>
        
        <div style="clear:both;height:15px;"></div>
        <div style="margin-bottom:10px;clear:both;">
          <div style="float:left;font-size:12px;">
            {% trans "E-Mail" %}
          </div>
          <div style="float:right;width:280px;">
            <input id="id_email" class="form-control" type="text" name="email" maxlength="50">
            <span style="font-size:12px;">({% trans "required" %}) ({% trans "will not be published" %})</span>
          </div>
        </div>
        
        <div style="clear:both;height:10px;"></div>
        <div style="margin-bottom:10px;clear:both;">
          <div style="float:left;">
            <input type="checkbox" class="form-control" id="id_feedback_allowed" name="feedback_allowed">
          </div>
          <div style="float:right;width:280px;font-size:12px;">
            {% trans "The operator of this website is allowed to inquire via email on questions about this comment" %}
          </div>
        
        </fieldset>
      </div>
    </div>
    <div style="clear:both;height:20px;"></div>
    
    {% with dialog="CommentModal" %}
    {% include "dialogs/more_cos_input.html" %}
    {% endwith %}
    
    <br>
    <div style="text-align:left;float:left;" id="error_msg_box">
    </div>
    <div style="text-align:left;float:right;">
    <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">{% trans "Close" %}</button>
    <input id="comment_form_submit_btn" name="comment_form" type="submit" class="btn btn-primary" value="{% trans "Send comment" %}" />
    </div>
    <div style="clear:both;"></div>
  </div>
  <div style="background-color: #222;height:275px;">
    &nbsp;
  </div>
    
  </div>
  </form>

  </div>
  </div>
  
</div>

<script type="text/javascript">
   $(document).ready(function() {
      $('#CommentModal').modal({
         keyboard: false,
         {% if form.is_bound %}show: true{% else %}show: false{% endif %}
      })
   });
   
   $('#CommentModal').on('shown', function() {
      if($('#CommentModal #id_co1_page').length != 0) {
        $('#CommentModal #co1_header_page').html(', {% trans "Page" %} ' + PDFViewer.pageNum);
        $('#CommentModal #id_co1_page').val(PDFViewer.pageNum);
      };
   });
   
   $('#comment_form_submit_btn').click(function(event) {
      if ($('#CommentModal #id_comment').val() == '') {
         $('#CommentModal #error_msg_box').html('<div class="alert alert-error">{% trans "Please enter a comment." %}</div>');
         $('#CommentModal #id_comment').focus();
         event.preventDefault();
         return false;
      }
      if ($('#CommentModal #id_comment').val().length > 800) {
         $('#CommentModal #error_msg_box').html('<div class="alert alert-error">{% blocktrans with 800 as max_size %}Comment too long (max. {{ max_size }} chars).{% endblocktrans %}</div>');
         $('#CommentModal #id_comment').focus();
         event.preventDefault();
         return false;
      }
      if ($('#CommentModal #id_username').val() == '') {
         $('#CommentModal #error_msg_box').html('<div class="alert alert-error">{% trans "Please enter your name." %}</div>');
         $('#CommentModal #id_username').focus();
         event.preventDefault();
         return false;
      }
      if ($('#CommentModal #id_email').val() == '') {
         $('#CommentModal #error_msg_box').html('<div class="alert alert-error">{% trans "Please enter your email adress." %}</div>');
         $('#CommentModal #id_email').focus();
         event.preventDefault();
         return false;
      }
      var regex = /^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
      if (!regex.test($('#CommentModal #id_email').val())) {
         $('#CommentModal #error_msg_box').html('<div class="alert alert-error">{% trans "The email adress you entered is invalid." %}</div>');
         $('#CommentModal #id_email').focus();
         event.preventDefault();
         return false;
      }
      for (var num_id=2;num_id<=counter_more_cos+1;num_id++) {
        var id = '#CommentModal #id_co' + num_id + '_page';
        if($(id).length != 0) {
          if($(id).val() == '') {
             $('#CommentModal #error_msg_box').html('<div class="alert alert-error">{% trans "Please provide a page number." %}</div>');
             $(id).focus();
             event.preventDefault();
             return false;
          }
          var regex = /^[0-9]+$/;
          if (!regex.test($(id).val())) {
             $('#CommentModal #error_msg_box').html('<div class="alert alert-error">{% trans "Invalid page number." %}</div>');
             $(id).focus();
             event.preventDefault();
             return false;
          }
        }
      }
      
   });
   
</script>

public_project/templates/dialogs/generic_confirm.html
{% load i18n %}

<div class="modal fade" id="genericConfirm">
  <div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-body">
    <p>{{ confirm_text }}</p>
  </div>
  <div class="modal-footer">
    <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">{% trans "Close" %}</button>
  </div>
  </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $('#genericConfirm').modal({
      keyboard: false,
      show: true
    })
  });
</script>

public_project/templates/dialogs/research_request.html
{% load i18n %}
{% load bpw %}

{% if research_request_form_status == 'SENT' %}
  {% trans "The research request was saved." as confirm_text %}
  {% include "dialogs/generic_confirm.html" %}   
{% endif %}
{% if research_request_form_status == 'FAILED' %}
  {% trans "There was an error and the research request could not be safed. Sorry! :-/" as confirm_text %}
  {% include "dialogs/generic_confirm.html" %}   
{% endif %}

<div class="modal fade" id="ResearchRequestModal">
  
  <div class="modal-dialog">
  <div class="modal-content" style="width:800px;">

  <div class="modal-header" style="background-color:#f9f9f9;">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3>{% trans "Research Request" %}</h3>
    <h4><i class="{{ commented_object1.get_icon_class }}"></i> {{ commented_object1 }}<span id="co1_header_page"></span></h4>
  </div>
  
  <form enctype="multipart/form-data" class="form-horizontal" action="." method="post">
    <input type="hidden" id="id_co1_content_type" name="co1_content_type" value="{{ commented_object1|modelname }}">
    <input type="hidden" id="id_co1_id" name="co1_id" value="{{ commented_object1.id }}">
    {% with commented_object1|modelname as modelname %}
    {% if modelname == 'document' %}
       <input type="hidden" id="id_co1_page" name="co1_page" value="">
    {% endif %}
    {% endwith %}
  {% csrf_token %}
  <div class="modal-body" style="padding:0px;max-height:inherit;background-color: #fff;">
    <div style="padding:15px;">
    <div style="margin-top:10px;">
      <div style="float:left;margin-right:20px;">
      <textarea id="id_description" class="form-control" style="width: 400px;height: 160px;" rows="10" cols="40" name="description"></textarea>
      </div>
      <div>
        <fieldset>
          
        <div style="margin-bottom:10px;clear:both;">
          <div style="float:left;font-size:12px;">
            Nr
          </div>
          <div style="float:right;width:280px;">
            <input id="id_nr" class="form-control" type="text" style="width:50px;" name="nr" maxlength="8"><br>
            <span style="font-size:12px;">
              ({% trans 'Give a unique number to your request so that people can reference it (e.g. "R1", "R2",...)' %})</span>
          </div>
        </div>
        
        <div style="clear:both;height:15px;">
          <div style="float:left;font-size:12px;">
            Title
          </div>
          <div style="float:right;width:280px;">
            <textarea id="id_title" class="form-control" rows="3" cols="50" name="title"></textarea>
          </div>
        </div>
        
        <div style="clear:both;"></div>
        
        </fieldset>
      </div>
    </div>
    <div style="clear:both;height:20px;"></div>
    
    {% with dialog="ResearchRequestModal" %}
    {% include "dialogs/more_cos_input.html" %}
    {% endwith %}
    <br>
    <div style="text-align:left;float:left;" id="error_msg_box">
    </div>
    <div style="text-align:left;float:right;">
    <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">{% trans "Close" %}</button>
    <input id="research_request_form_submit_btn" name="research_request_form" type="submit" class="btn btn-primary" value="{% trans "Save Research Request" %}" />
    </div>
    <div style="clear:both;"></div>
  </div>  
    <div style="background-color: #222;height:275px;">
      &nbsp;
    </div>
    
  </div>
  </form>
  
  </div>
  </div>

</div>

<script type="text/javascript">
   $(document).ready(function() {
      $('#ResearchRequestModal').modal({
         keyboard: false,
         {% if form.is_bound %}show: true{% else %}show: false{% endif %}
      })
   });
   
   $('#ResearchRequestModal').on('shown', function() {
      if($('#ResearchRequestModal #id_co1_page').length != 0) {
        $('#ResearchRequestModal #co1_header_page').html(', {% trans "Page" %} ' + PDFViewer.pageNum);
        $('#ResearchRequestModal #id_co1_page').val(PDFViewer.pageNum);
      };
   });
   
   $('#research_request_form_submit_btn').click(function(event) {
      if ($('#ResearchRequestModal #id_description').val() == '') {
         $('#ResearchRequestModal #error_msg_box').html('<div class="alert alert-error">{% trans "Field is mandatory." %}</div>');
         $('#ResearchRequestModal #id_description').focus();
         event.preventDefault();
         return false;
      }
      if ($('#ResearchRequestModal #id_title').val() == '') {
         $('#ResearchRequestModal #error_msg_box').html('<div class="alert alert-error">{% trans "Field is mandatory." %}</div>');
         $('#ResearchRequestModal #id_title').focus();
         event.preventDefault();
         return false;
      }
      if ($('#ResearchRequestModal #id_nr').val() == '') {
         $('#ResearchRequestModal #error_msg_box').html('<div class="alert alert-error">{% trans "Field is mandatory." %}</div>');
         $('#ResearchRequestModal #id_nr').focus();
         event.preventDefault();
         return false;
      }
      
      for (var num_id=2;num_id<=counter_more_cos+1;num_id++) {
        var id = '#ResearchRequestModal #id_co' + num_id + '_page';
        if($(id).length != 0) {
          if($(id).val() == '') {
             $('#ResearchRequestModal #error_msg_box').html('<div class="alert alert-error">{% trans "Please provide a page number." %}</div>');
             $(id).focus();
             event.preventDefault();
             return false;
          }
          var regex = /^[0-9]+$/;
          if (!regex.test($(id).val())) {
             $('#ResearchRequestModal #error_msg_box').html('<div class="alert alert-error">{% trans "Invalid page number." %}</div>');
             $(id).focus();
             event.preventDefault();
             return false;
          }
        }
      }
      
   });
   
</script>